name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  merge_group: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: pnpm

      - name: Setup
        run: npm i -g @nyxb/nyxi

      - name: Install
        run: nyxci

      - name: Lint
        run: nyxr lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18.18.2, lts/*]
        include:
          - os: macos-latest
            node_version: lts/*
          - os: windows-latest
            node_version: lts/*
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - run: corepack enable

      - name: Setup
        run: npm i -g @nyxb/nyxi

      - name: Install
        run: nyxci

      - name: Build
        run: nyxr build

      - name: Test
        run: nyxr test

      - name: Typecheck
        run: nyxr typecheck
